repos:
-   hooks:
    -   id: pre-commit-update
        args:
        -   --verbose
    repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.1.0
-   hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
-   hooks:
    -   id: ruff
        args:
        -   --config=pyproject.toml
        -   --fix
        -   --exit-non-zero-on-fix
    -   id: ruff-format
        args:
        -   --config=pyproject.toml
        types_or: [python, jupyter]
    repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.8
-   hooks:
    -   id: mypy
        args:
        -   --config=pyproject.toml
        additional_dependencies:
        -   types-requests
        -   types-toml
        -   types-pytz
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
