name: check_formatting

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/check_formatting.yml"
      - "spotify/**"
      - "scripts/**"
      - "tests/**"
      - "notebooks/**"
      - "setup.py"
      - "pyproject.toml"

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run formatting checks
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/development.txt
          black --check --diff --color .
          ruff format --check .
          ruff check .
          mypy .
